### ISSUE TITLE
Linux: Fortran make trouble using gfortran (ifort worked)

### ISSUE THREAD

**Issue by keflavich** [hyperion-rt/hyperion#23]
On a linux machine, I've successfully installed all of the dependencies as far as I can tell - h5py imports, mpif90 exists and looks healthy.  

When I tried to ./configure & make the fortran binaries, I ran into a very long list of errors, leading with:

```
$ make 
h5fc -Jsrc/modules -Isrc/modules -g -ffree-line-length-none    src/mpi/mpi_core_nompi.f90 fortranlib/src/posix_default.f90 fortranlib/src/base_types.f90 fortranlib/src/lib_messages.f90 fortranlib/src/lib_io
 In file fortranlib/src/posix_default.f90:3

  use iso_c_binding
                  1
Fatal Error: Can't open module file 'iso_c_binding.mod' for reading at (1): No such file or directory
```

This only happened with the gfortran compiler.  When I switched to the ifort compiler (which required re-installing the dependencies with ifort included in my path), there were no errors.

This is a non-urgent bug, but I figured it's worth reporting because of the apparent incompatibility with gfortran.  I also wonder if general gfortran incompatibility issues might explain my mac install issues.

**Comment by fometeo** [comment]
gfortran test.f90 -o test.exe
use modulename
  1
Fatal Error: Can't open module file 'modulename.mod' for reading at (1): No such file or directory
if file modulename.mod is at /usr/local/include and libraries at /usr/local/lib
such error goes away using:
gfortran test.f90 -o test.exe -I/usr/local/include -L/usr/local/lib
